version: '2'

services:
  weba_postgres:
      image: postgres:9.6
      container_name: weba_postgres
      hostname: weba_postgres
      ports:
        - "5432:5432"
      env_file:
        - ../env/development.env
      volumes:
        - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
        - ../data/postgres:/var/lib/postgresql/data/pgdata
      networks:
        weba:
            ipv4_address: 100.0.0.10

  weba_zookeeper:
      image: wurstmeister/zookeeper:3.4.6
      container_name: weba_zookeeper
      ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
      networks:
        weba:
          ipv4_address: 100.0.0.11

  weba_kafka:
      image: wurstmeister/kafka:0.9.0.1
      container_name: weba_kafka
      ports:
        - "9092:9092"
        - "9999:9999"
      links:
        - weba_zookeeper
      env_file:
        - ../env/development.env
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        weba:
          ipv4_address: 100.0.0.12

  weba_kafka_manager:
      image: sheepkiller/kafka-manager:1.3.1.6
      container_name: weba_kafka_manager
      hostname: weba_kafka_manager
      links:
        - weba_zookeeper
        - weba_kafka
      ports:
        - "9000:9000"
      env_file:
        - ../env/development.env
      networks:
        weba:
          ipv4_address: 100.0.0.13

  weba_entrypoint:
      container_name: weba_entrypoint
      build: entrypoint
      hostname: weba_entrypoint
      links:
         - weba_kafka
      ports:
         - 80:80
      env_file:
        - ../env/development.env
      networks:
        weba:
          ipv4_address: 100.0.0.14

  weba_flink_jobmanager:
      build: flink
      container_name: weba_flink_jobmanager
      hostname: weba_flink_jobmanager
      ports:
        - 48080:8080
        - 6123:6123
      expose:
        - 22
      command: /usr/local/flink/bin/config-flink.sh weba_flink_jobmanager
      links:
        - weba_kafka
        - weba_zookeeper
      env_file:
        - ../env/development.env
      networks:
        weba:
          ipv4_address: 100.0.0.17

  weba_flink_worker:
      build: flink
      container_name: weba_flink_worker
      hostname: weba_flink_worker
      expose:
        - 6121
        - 6122
      ports:
        - 6121:6121
        - 6122:6122
      links:
        - weba_flink_jobmanager
        - weba_kafka
        - weba_zookeeper
      command: /usr/local/flink/bin/config-flink.sh weba_flink_worker
      env_file:
        - ../env/development.env
      networks:
        weba:
          ipv4_address: 100.0.0.18

  weba_locust:
      container_name: weba_locust
      build: locust
      hostname: weba_locust
      links:
        - weba_entrypoint
      ports:
        - 8089:8089
      env_file:
        - ../env/development.env
      networks:
        weba:
          ipv4_address: 100.0.0.19

  weba_druid_overlord:
    image: znly/druid:0.9.1.1
    container_name: weba_druid_overlord
    env_file:
      - ../env/development.env
    links:
      - weba_postgres
      - weba_zookeeper
    volumes:
      - ./druid/_common/common.runtime.properties/:/opt/druid/conf/druid/_common/common.runtime.properties
    command:
      - overlord
    ports:
      - "58090:8090"
    networks:
      weba:
        ipv4_address: 100.0.0.21

  weba_druid_coordinator:
    image: znly/druid:0.9.1.1
    container_name: weba_druid_coordinator
    env_file:
      - ../env/development.env
    links:
      - weba_postgres
      - weba_zookeeper
    volumes:
      - ./druid/_common/common.runtime.properties/:/opt/druid/conf/druid/_common/common.runtime.properties
    command:
      - coordinator
    ports:
      - "58081:8081"
    networks:
      weba:
        ipv4_address: 100.0.0.22

  weba_druid_middlemanager:
    image: znly/druid:0.9.1.1
    container_name: weba_druid_middlemanager
    env_file:
      - ../env/development.env
    ports:
      - "58091:8091"
    links:
      - weba_postgres
      - weba_zookeeper
    volumes:
      - ./druid/_common/common.runtime.properties/:/opt/druid/conf/druid/_common/common.runtime.properties
    command:
      - middleManager
    networks:
      weba:
        ipv4_address: 100.0.0.23

  weba_druid_historical:
    image: znly/druid:0.9.1.1
    container_name: weba_druid_historical
    env_file:
      - ../env/development.env
    ports:
      - "58083:8083"
    links:
      - weba_postgres
      - weba_zookeeper
    volumes:
      - ./druid/_common/common.runtime.properties/:/opt/druid/conf/druid/_common/common.runtime.properties
    command:
      - historical
    networks:
      weba:
        ipv4_address: 100.0.0.24

  weba_druid_broker:
    image: znly/druid:0.9.1.1
    container_name: weba_druid_broker
    env_file:
      - ../env/development.env
    ports:
      - "58082:8082"
    links:
      - weba_postgres
      - weba_zookeeper
    volumes:
      - ./druid/_common/common.runtime.properties/:/opt/druid/conf/druid/_common/common.runtime.properties
    command:
      - broker
    networks:
      weba:
          ipv4_address: 100.0.0.25

  weba_superset:
    image: amancevice/superset
    container_name: weba_superset
    env_file:
      - ../env/development.env
    volumes:
      - "./superset/superset_config.py:/home/superset/superset_config.py"
      - "../data/superset/db:/home/superset/db"
    links:
      - weba_druid_broker
      - weba_druid_coordinator
      - weba_redis
      - weba_postgres
    ports:
      - "58088:8088"
    networks:
      weba:
        ipv4_address: 100.0.0.26

  weba_redis:
    container_name: weba_redis
    image: redis:alpine
    hostname: weba_redis
    restart: always
    volumes:
      - ../data/redis:/data
    networks:
      weba:
        ipv4_address: 100.0.0.27

networks:
  weba:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 100.0.0.0/24
        gateway: 100.0.0.1