zookeeper:
  image: wurstmeister/zookeeper
  container_name: zookeeper
  hostname: zookeeper
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka:0.9.0.1
  container_name: kafka
  ports:
    - "9092:9092"
    - "9999:9999"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 100.0.0.205
    KAFKA_CREATE_TOPICS: "webaio_entrypoint:2:1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    JMX_PORT: 9999
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka_manager:
    image: sheepkiller/kafka-manager
    container_name: kafka_manager
    hostname: kafka_manager
    links:
        - zookeeper:zk
        - kafka
    ports:
        - "9002:9000"
    environment:
        ZK_HOSTS: "zookeeper:2181"
        KM_VERSION: "1.3.0.8"
        KM_REVISION: "6e196ea7a332471bead747535f9676f0a2bad008"

webaio_entrypoint:
    container_name: webaio_entrypoint
    build: webaio_entrypoint
    hostname: webaio_entrypoint
    links:
       - kafka
    ports:
        - 80:80
    volumes:
        - /webaio/docker/webaio_entrypoint:/webaio/docker/webaio_entrypoint
    environment:
        FLUME_CONF_FILE: /opt/flume/conf/flume.conf
        FLUME_AGENT_NAME: a1
        FLUME_PLUGINS_DIRECTORY: /opt/flume/plugins.d/
        FLUME_JAVA_OPTIONS: "-Xms1024m -Xmx2048m -Xss256k -XX:MaxDirectMemorySize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC"

elasticsearch:
    image: elasticsearch:2.2
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
        - 9200:9200
        - 9300:9300

kibana:
    image: kibana:4.4.1
    container_name: kibana
    hostname: kibana
    ports:
        - 5601:5601
    links:
        - elasticsearch

redis:
    image: redis:3.0.7-alpine
    container_name: redis
    hostname: redis
    ports:
        - 6379:6379