eventor_webserver:
  container_name: eventor_webserver
  build: eventor_webserver
  hostname: eventor_webserver
  ports:
    - 80:80
  volumes:
    - /webaio/docker/eventor_webserver:/webaio/docker/eventor_webserver
    - /webaio/var/logs/requests:/var/log/requests
    - /webaio/var/logs/nginx:/var/log/nginx

eventor_flume:
    container_name: eventor_flume
    build: eventor_flume
    hostname: eventor_flume
    links:
        - eventor_webserver
        - kafka
    volumes_from:
        - eventor_webserver
    volumes:
        - /webaio/var/logs/flume:/var/log/flume
    environment:
        FLUME_CONF_FILE: /opt/flume/conf/flume.conf
        FLUME_AGENT_NAME: a1
        FLUME_PLUGINS_DIRECTORY: /opt/flume/plugins.d/

zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
        - "2181:2181"

kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
        - "9092:9092"
    links:
        - zookeeper
    environment:
        KAFKA_ADVERTISED_HOST_NAME: "100.0.0.205"
        KAFKA_CREATE_TOPICS: "eventor_webserver:1:1"
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

kafka_manager:
    image: sheepkiller/kafka-manager
    container_name: kafka_manager
    hostname: kafka_manager
    ports:
        - "9000:9000"

metrics_storm_nimbus:
    image: wurstmeister/storm-nimbus
    ports:
        - "49773:3773"
        - "49772:3772"
        - "49627:6627"
        - "22"
    links:
        - zookeeper

metrics_storm_supervisor:
    image: wurstmeister/storm-supervisor
    ports:
        - "8000"
        - "22"
    links:
        - metrics_storm_nimbus:nimbus
        - zookeeper

metrics_storm_ui:
    image: wurstmeister/storm-ui
    ports:
        - "49080:8080"
        - "22"
    links:
        - metrics_storm_nimbus:nimbus
        - zookeeper

metrics_elasticsearch:
    image: elasticsearch:2.2
    ports:
        - "9200:9200"
        - "9300:9300"

metrics_kibana:
    image: kibana:4.4.1
    ports:
        - "5601:5601"
    links:
        - metrics_elasticsearch:elasticsearch

tracker:
    build: tracker
    container_name: tracker
    ports:
        - "8081:8081"
    volumes:
        - ../../tracker:/tracker

piwik:
    build: piwik/lamp
    container_name: piwik
    ports:
        - "81:80"
        - "3306:3306"
    volumes:
        - /webaio/piwik:/app