Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.box_check_update = true
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: "100.0.0.205"
  config.vm.synced_folder "../", "/weba", type: "nfs", nfs_udp: false, nfs_export: true

  config.vm.provider "virtualbox" do |v|
    v.name = "weba"
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y vim-nox
    docker events&
    echo "\n" >> .bashrc
    echo "alias weba_entrypoint='docker exec -it weba_entrypoint /bin/bash'" >> .bashrc
    echo "alias weba_kafka='docker exec -it weba_kafka /bin/bash'" >> .bashrc
    echo "alias reload-docker-configuration='docker-compose stop && docker-compose rm -f && docker-compose build && docker-compose up -d'" >> .bashrc
    echo "\n" >> .bashrc
  SHELL
end